version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: khoahoc
      MYSQL_ROOT_PASSWORD: password

  springboot-app:
    build: .
    image: kttkpm-springboot-app
    ports:
      - 9090:8080
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/khoahoc?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
